export const RegistrationsActionTypes = {
    LOAD_REGISTRATIONS: 'LOAD_REGISTRATIONS',
    CLEAR_REGISTRATIONS: 'CLEAR_REGISTRATIONS',
    ADD_REGISTRATION: 'ADD_REGISTRATION',
    REMOVE_REGISTRATION: 'REMOVE_REGISTRATION',
};
