export const RegistrationsActionTypes = {
    LOAD_REGISTRATIONS: 'LOAD_REGISTRATIONS',
    CLEAR_REGISTRATIONS: 'CLEAR_REGISTRATIONS',
    ADD_REGISTRATION: 'ADD_REGISTRATION',
    REMOVE_REGISTRATION: 'REMOVE_REGISTRATION',
    LOAD_TEMP_REGISTRATION: 'LOAD_TEMP_REGISTRATION',
    CLEAR_TEMP_REGISTRATION: 'CLEAR_TEMP_REGISTRATION',
    ADD_EVENT_REGISTRATION: 'ADD_EVENT_REGISTRATION',
    REMOVE_EVENT_REGISTRATION: 'REMOVE_EVENT_REGISTRATION',
    LOAD_EVENT_REGISTRATIONS: 'LOAD_EVENT_REGISTRATIONS',
    CLEAR_EVENT_REGISTRATIONS: 'CLEAR_EVENT_REGISTRATIONS',
    GET_EVENT_REGISTRATIONS: 'GET_EVENT_REGISTRATIONS',
};
