export const StateLeadActionTypes = {
    LOAD_LEAD_RALLIES: 'LOAD_LEAD_RALLIES',
    CLEAR_LEAD_RALLIES: 'CLEAR_LEAD_RALLIES',
    LOAD_LEAD_DONE_RALLIES: 'LOAD_LEAD_DONE_RALLIES',
    CLEAR_LEAD_DONE_RALLIES: 'CLEAR_LEAD_DONE_RALLIES',
    CLEAR_STATE_LEAD: 'CLEAR_STATE_LEAD',
};
