export const PateActionTypes = {
    SET_SPINNER: 'SET_SPINNER',
    CLEAR_SPINNER: 'CLEAR_SPINNER',
    SET_RALLY: 'SET_RALLY',
    CLEAR_RALLY: 'CLEAR_RALLY',
    SET_PATE_REGISTRATION: 'SET_PATE_REGISTRATION',
    CLEAR_PATE_REGISTRATION: 'CLEAR_PATE_REGISTRATION'
};
