export const PateActionTypes = {
    SET_SPINNER: 'SET_SPINNER',
    CLEAR_SPINNER: 'CLEAR_SPINNER',
    SET_RALLY: 'SET_RALLY',
    CLEAR_RALLY: 'CLEAR_RALLY',
    SET_PATE_REGISTRATION: 'SET_PATE_REGISTRATION',
    CLEAR_PATE_REGISTRATION: 'CLEAR_PATE_REGISTRATION',
    LOAD_REGISTERED_USERS: 'LOAD_REGISTERED_USERS',
    LOAD_TMP_USER: 'LOAD_TMP_USER',
    CLEAR_TMP_USER: 'CLEAR_TMP_USER',
    // UPDATE_USER_WITH_PROFILE: 'UPDATE_USER_WITH_PROFILE'
};
