export const PateActionTypes = {
    SET_SPINNER: 'SET_SPINNER',
    CLEAR_SPINNER: 'CLEAR_SPINNER',
    SET_RALLY: 'SET_RALLY',
    CLEAR_RALLY: 'CLEAR_RALLY',
    SET_REGISTRATION: 'SET_REGISTRATION',
    CLEAR_REGISTRATION: 'CLEAR_RESERVATION'
};
