export const UserActionTypes = {
    SET_USER: 'SET_USER',
    UPDATE_USER: 'UPDATE_USER',
    CLEAR_USER: 'CLEAR_USER',
    ADD_REGISTRATION_TO_CURRENT_USER: 'ADD_REGISTRATION_TO_CURRENT_USER',
    REMOVE_REGISTRATION_FROM_CURRENT_USER:
        'REMOVE_REGISTRATION_FROM_CURRENT_USER',
};
