// const UserActionTypes = {
//   SET_CURRENT_USER: 'SET_CURRENT_USER',
//   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
//   UPDATE_USER: 'UPDATE_USER',
//   LOGIN_FAILURE: 'LOGIN_FAILURE',
//   LOGIN_FAIL: 'LOGIN_FAIL'
// };
// export default UserActionTypes;
export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    UPDATE_USER: 'UPDATE_USER',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_FAIL: 'LOGIN_FAIL',
    CLEAR_USER: 'CLEAR_USER',
};
